version: '3'
# docker-compose -p "barbearia-api" up -d
services:
  barbearia-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      PostgresSQL:
        condition: service_healthy
    restart: on-failure
    networks:
      - rede
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresSQL:5432/barbershop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
  PostgresSQL:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=barbershop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rede
    volumes:
      - pg-data:/docker-entrypoint-initdb.d

volumes:
  pg-data:
networks:
  rede:
    driver: bridge